# Creating array

In [1]:
import numpy as np

In [2]:
#One Dimensional Array
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
#Two Dimensional Array
np.array([(1,2,3,4),(5,6,7,8)])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
#1D array of length 4 all values 0
np.zeros(4)

array([0., 0., 0., 0.])

In [5]:
# 4x4 array with all values 1
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
#4x4 array of 0 with 1 on diagonal (Identity matrix)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
#Array of 4 evenly divided values from 0 to 100
np.linspace(0,100,4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [8]:
#Array of values from 0 to less than 20 with step 4
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [9]:
#4x4 array with all values 8
np.full((4,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [10]:
#4x5 array of random floats between 0–1
np.random.rand(4,5)

array([[0.62022914, 0.98854374, 0.0399373 , 0.96115051, 0.47235411],
       [0.72390907, 0.40008545, 0.92401838, 0.47341422, 0.89391482],
       [0.33276185, 0.94363016, 0.24156402, 0.38128461, 0.48584302],
       [0.40839656, 0.75071643, 0.38704037, 0.71393075, 0.52371721]])

In [11]:
#4x5 array of random floats between 0–100
np.random.rand(4,5)*100

array([[65.13505432, 96.27622518, 15.47789641, 36.1745597 , 33.17614435],
       [53.15732698, 61.16945354, 69.01097431, 12.84894358,  1.54053087],
       [29.394416  , 84.82668586, 63.57300252, 72.0217981 , 46.55854267],
       [ 0.1386284 , 99.66896548, 61.31970766, 16.57096875, 57.06113482]])

In [12]:
#2x3 array with random ints between 0–4
np.random.randint(4,size=(2,3))

array([[0, 1, 3],
       [1, 2, 2]])

# Inspecting Properties

In [13]:
arr=np.array([(1,2,3,4),(5,6,7,8)])

In [14]:
#Returns number of elements in arr
arr.size

8

In [15]:
#Returns dimensions of arr (rows,columns)
arr.shape

(2, 4)

In [16]:
#Returns type of elements in arr
arr.dtype

dtype('int32')

In [17]:
#Convert arr elements to type dtype
arr.astype(float)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [18]:
#Convert arr to a Python list
arr.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [19]:
#View documentation for np.eye
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

# Copying/sorting/reshaping

In [20]:
#Copies arr to new memory
arr1=np.copy(arr)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
#Sorts arr
arr.sort()

In [22]:
#Sorts specific axis of arr
arr.sort(axis=0)

In [23]:
# Flattens 2D array two_d_arr to 1D
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
#Transposes arr (rows become columns and vice versa)
arr.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [25]:
#Reshapes arr to 3 rows, 4 columns without changing data
arr3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr3.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Adding Elements

In [26]:
#Appends values to end of arr
np.append(arr,10)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [27]:
# Inserts values into arr before index 2
np.insert(arr,2,15)

array([ 1,  2, 15,  3,  4,  5,  6,  7,  8])

# Combining/splitting

In [28]:
arr1=np.array([(1,2,3),(4,5,6)])
arr2=np.array([(7,8,9),(10,11,12)])

In [29]:
# Adds arr2 as rows to the end of arr1
np.concatenate((arr1,arr2),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
#Adds arr2 as columns to end of arr1
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [31]:
#Splits arr into 3 sub-arrays
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np.split(arr,3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [32]:
#Splits arr6 horizontally on the 5th index
arr6=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
np.hsplit(arr6,5)

[array([1, 2, 3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11, 12]),
 array([13, 14, 15, 16]),
 array([17, 18, 19, 20])]

# Indexing/slicing/subsetting

In [33]:
#Returns the element at index 4
arr[4]

5

In [34]:
#Assigns array element on index 1 the value 4
arr[1]=4

In [35]:
arr

array([ 1,  4,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
#Returns an array with boolean values
arr<5

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False])

In [37]:
#Inverts a boolean array
~arr

array([ -2,  -5,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13],
      dtype=int32)

# Scalar Math

In [38]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#Add 4 to each array element
np.add(arr,4)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [39]:
#Subtract 4 from each array element
np.subtract(arr,4)

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [40]:
#Multiply each array element by 3
np.multiply(arr,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36])

In [41]:
# Divide each array element by 4
np.divide(arr,4)

array([0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75,
       3.  ])

In [42]:
#Raise each array element to the 5th power
np.power(arr,5)

array([     1,     32,    243,   1024,   3125,   7776,  16807,  32768,
        59049, 100000, 161051, 248832], dtype=int32)

# Vector Math

In [43]:
#Elementwise add arr2 to arr1
np.add(arr1,arr2)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [44]:
#Elementwise subtract arr2 from arr1
np.subtract(arr1,arr2)

array([[-6, -6, -6],
       [-6, -6, -6]])

In [45]:
#Elementwise multiply arr1 by arr2
np.multiply(arr1,arr2)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [46]:
#Elementwise divide arr1 by arr2
np.divide(arr1,arr2)

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [47]:
# Elementwise raise arr1 raised to the power of arr2
np.power(arr1,arr2)

array([[          1,         256,       19683],
       [    1048576,    48828125, -2118184960]], dtype=int32)

In [48]:
#Returns True if the arrays have the same elements and shape
np.array_equal(arr1,arr2)

False

In [49]:
#Square root of each element in the array
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162])

In [50]:
#Sine of each element in the array
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292])

In [51]:
#Natural log of each element in the array
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665])

In [52]:
#Absolute value of each element in the array
np.abs(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
#Rounds up to the nearest int
np.ceil(arr)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [54]:
#Rounds down to the nearest int
np.floor(arr)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [55]:
#Rounds to the nearest int
np.round(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Statistics

In [56]:
#Returns mean along specific axis
np.mean(arr,axis=0)

6.5

In [57]:
#Returns sum of arr
arr.sum()

78

In [58]:
# Returns minimum value of arr
arr.min()

1

In [59]:
# Returns maximum value of specific axis
arr.max(axis=0)

12

In [60]:
#Returns the variance of array
np.var(arr)

11.916666666666666